---
- hosts: benchservers
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - name: download from git repo
      git:
        repo: '{{ item.repo }}'
        dest: '{{ item.dest }}'
        update: yes
      with_items:
        - repo: https://github.com/sstephenson/rbenv.git
          dest: /home/isucon/.rbenv
        - repo: https://github.com/sstephenson/ruby-build.git
          dest: /home/isucon/.rbenv/plugins/ruby-build
    - name: set env
      blockinfile:
        dest: /home/isucon/.bashrc
        insertafter: '^PATH=\$PATH:\$HOME/bin$'
        content: |
          export RBENV_ROOT=/home/isucon/.rbenv
          export PATH="$RBENV_ROOT/bin:$PATH"
          eval "$(rbenv init -)"

    - name: check rbenv version
      shell: bash -lc "rbenv versions | grep 2.3.0"
      register: rbenv_check_install
      changed_when: False
      ignore_errors: yes
    - name: install ruby
      shell: bash -lc "rbenv install -v 2.3.0"
      when: rbenv_check_install|failed
    - name: set default ruby version
      shell: bash -lc "rbenv global 2.3.0"

    - name: install bundler
      shell: bash -lc "rbenv exec gem install bundler && rbenv rehash"

- hosts: benchservers
  sudo: yes
  gather_facts: no
  tasks:
    # java
    - apt:
        name: openjdk-8-jdk
        state: present
    # gradle
    - apt:
        name: gradle
        state: present
